import { Injectable } from '@angular/core';
import type { Observable } from 'rxjs';
import { HydraApiService } from '@core/api';
import type {
  ConfirmTotpInput,
  ConfirmTotpOutput,
  DisableTotpInput,
  DisableTotpOutput,
  SetupTotpOutput,
} from '@features/account/models';

/**
 * Service TotpService
 * @class TotpService
 * @extends {HydraApiService}
 *
 * @description
 * Account-owned API service for the authenticator app (TOTP) enrollment
 * lifecycle exposed by the `Otp` module: generating a pending secret
 * (`setup`), activating it with a verification code (`confirm`), and
 * disabling an active enrollment with a proof-of-possession code (`disable`).
 *
 * @version 2.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
@Injectable({ providedIn: 'root' })
export class TotpService extends HydraApiService {
  /**
   * Constant BASE_PATH
   * @readonly
   * @static
   *
   * @description
   * Base path for the TOTP resource exposed by the `Otp` module.
   *
   * @type {string}
   */
  private static readonly BASE_PATH: string = '/api/otp/totp';

  /**
   * Method setup
   *
   * @description
   * Requests a new TOTP secret and `otpauth://` provisioning URI for
   * authenticator app enrollment. Persists it server-side as a pending
   * enrollment; calling this again replaces the previous pending secret.
   *
   * @returns {Observable<SetupTotpOutput>} Observable emitting the generated secret and URI.
   */
  public setup(): Observable<SetupTotpOutput> {
    return this.postAction<SetupTotpOutput>(`${TotpService.BASE_PATH}/setup`);
  }

  /**
   * Method confirm
   *
   * @description
   * Verifies a code from the authenticator app against the pending secret
   * and, on success, activates TOTP for the authenticated user.
   *
   * @param {string} code - 6-digit code generated by the authenticator app.
   * @returns {Observable<ConfirmTotpOutput>} Observable emitting the activation result.
   */
  public confirm(code: string): Observable<ConfirmTotpOutput> {
    return this.post<ConfirmTotpInput, ConfirmTotpOutput>(`${TotpService.BASE_PATH}/confirm`, {
      code,
    });
  }

  /**
   * Method disable
   *
   * @description
   * Disables TOTP for the authenticated user. Requires a valid current TOTP
   * code as proof of possession.
   *
   * @param {string} code - Current 6-digit code from the authenticator app.
   * @returns {Observable<DisableTotpOutput>} Observable emitting the disable result.
   */
  public disable(code: string): Observable<DisableTotpOutput> {
    return this.post<DisableTotpInput, DisableTotpOutput>(`${TotpService.BASE_PATH}/disable`, {
      code,
    });
  }
}
