import { expect, type Page } from '@playwright/test';

/** Parsed transport object validated before its fields are consumed. */
export type JsonObject = Record<string, unknown>;

/** Retrieves a configured value without a development or production fallback. */
export function requiredEnvironment(name: string): string {
  const value = process.env[name];
  if (!value?.trim()) throw new Error(`Missing live integration setting: ${name}.`);
  return value;
}

/** Checks the JSON object boundary instead of trusting transport type assertions. */
export function object(value: unknown): JsonObject {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('Expected an API JSON object.');
  }
  return value as JsonObject;
}

/** Requires a nonempty transport string. */
export function text(value: JsonObject, key: string): string {
  const result = value[key];
  if (typeof result !== 'string' || !result) throw new Error(`Expected string field: ${key}.`);
  return result;
}

/** Requires the numeric optimistic concurrency revision emitted by the server. */
export function revision(value: JsonObject): number {
  const result = value['revision'];
  if (typeof result !== 'number' || !Number.isInteger(result) || result < 1) {
    throw new Error('Expected a positive resource revision.');
  }
  return result;
}

/** Parses the negotiated Hydra collection without accepting a missing collection as empty. */
export function members(value: JsonObject): JsonObject[] {
  const result = value['member'] ?? value['hydra:member'];
  if (!Array.isArray(result)) throw new Error('Expected a Hydra collection.');
  return result.map(object);
}

declare global {
  interface Window {
    fgLiveStream?: {
      controller: AbortController;
      opened: boolean;
      error?: string;
      events: unknown[];
    };
  }
}

/** Sends browser fetch requests so real CORS, cookies and multipart encoding remain in scope. */
export class LiveBrowserApi {
  public constructor(
    private readonly page: Page,
    private readonly baseUrl: string,
    private readonly token: string,
  ) {}

  /** Requests JSON using the actual backend and asserts the exact HTTP status. */
  public async json(
    method: string,
    path: string,
    status: number,
    payload?: JsonObject,
    currentRevision?: number,
  ): Promise<JsonObject> {
    const result = await this.page.evaluate(
      async (input) => {
        const headers: Record<string, string> = {
          Accept: 'application/ld+json',
          Authorization: `Bearer ${input.token}`,
          'Content-Type':
            input.method === 'PATCH' ? 'application/merge-patch+json' : 'application/ld+json',
        };
        if (input.revision !== undefined) headers['If-Match'] = `"revision-${input.revision}"`;
        const response = await fetch(input.url, {
          method: input.method,
          credentials: 'include',
          headers,
          body: input.payload === undefined ? undefined : JSON.stringify(input.payload),
        });
        return { status: response.status, body: await response.text() };
      },
      {
        url: new URL(path, this.baseUrl).href,
        token: this.token,
        method,
        payload,
        revision: currentRevision,
      },
    );
    // Error output never includes a login/token response.
    expect(result.status, `${method} ${path}`).toBe(status);
    return result.body ? object(JSON.parse(result.body)) : {};
  }

  /** Uploads FormData generated by Chromium without a hand-authored multipart header. */
  public async upload(path: string, contents: string): Promise<JsonObject> {
    const result = await this.page.evaluate(
      async (input) => {
        const body = new FormData();
        body.append(
          'file',
          new Blob([input.contents], { type: 'application/pdf' }),
          'live-evidence.pdf',
        );
        body.append('label', 'Live API integration evidence');
        const response = await fetch(input.url, {
          method: 'POST',
          credentials: 'include',
          headers: { Accept: 'application/ld+json', Authorization: `Bearer ${input.token}` },
          body,
        });
        return { status: response.status, body: await response.text() };
      },
      { url: new URL(path, this.baseUrl).href, token: this.token, contents },
    );
    expect(result.status, `POST ${path}`).toBe(201);
    return object(JSON.parse(result.body));
  }

  /** Downloads exact bytes through the owning resource's access-controlled content route. */
  public async download(path: string): Promise<string> {
    const result = await this.page.evaluate(
      async (input) => {
        const response = await fetch(input.url, {
          credentials: 'include',
          headers: { Authorization: `Bearer ${input.token}` },
        });
        return { status: response.status, contents: await response.text() };
      },
      { url: new URL(path, this.baseUrl).href, token: this.token },
    );
    expect(result.status, `GET ${path}`).toBe(200);
    return result.contents;
  }

  /** Opens the real private Mercure stream and keeps only parsed notification payloads in memory. */
  public async subscribe(hubUrl: string, topic: string, subscriberToken: string): Promise<void> {
    const url = new URL(hubUrl);
    url.searchParams.set('topic', topic);
    await this.page.evaluate(
      (input) => {
        const controller = new AbortController();
        const stream = {
          controller,
          opened: false,
          error: undefined as string | undefined,
          events: [] as unknown[],
        };
        window.fgLiveStream = stream;
        void (async () => {
          try {
            const response = await fetch(input.url, {
              headers: { Accept: 'text/event-stream', Authorization: `Bearer ${input.token}` },
              signal: controller.signal,
            });
            if (
              response.status !== 200 ||
              !response.body ||
              !response.headers.get('content-type')?.includes('text/event-stream')
            ) {
              throw new Error(`Mercure stream HTTP ${response.status}.`);
            }
            stream.opened = true;
            const reader = response.body.getReader();
            const decoder = new TextDecoder();
            let buffer = '';
            while (!controller.signal.aborted) {
              // eslint-disable-next-line no-await-in-loop -- Each SSE chunk depends on the preceding stream read.
              const chunk = await reader.read();
              if (chunk.done) break;
              buffer = (buffer + decoder.decode(chunk.value, { stream: true })).replace(
                /\r\n/g,
                '\n',
              );
              let end = buffer.indexOf('\n\n');
              while (end !== -1) {
                const event = buffer.slice(0, end);
                buffer = buffer.slice(end + 2);
                const data = event
                  .split('\n')
                  .filter((line) => line.startsWith('data:'))
                  .map((line) => line.slice(5).trimStart())
                  .join('\n');
                if (data) stream.events.push(JSON.parse(data));
                end = buffer.indexOf('\n\n');
              }
            }
          } catch (error) {
            if (!controller.signal.aborted)
              stream.error = error instanceof Error ? error.message : 'Mercure stream failed.';
          }
        })();
      },
      { url: url.href, token: subscriberToken },
    );
    await expect
      .poll(async () =>
        this.page.evaluate(() => ({
          opened: window.fgLiveStream?.opened,
          error: window.fgLiveStream?.error,
        })),
      )
      .toEqual({ opened: true, error: undefined });
  }

  /** Requires the delivered private SSE notification to match the durable REST notification. */
  public async expectNotification(notificationId: string): Promise<void> {
    await expect
      .poll(
        async () =>
          this.page.evaluate((id) => {
            const stream = window.fgLiveStream;
            if (stream?.error) throw new Error(stream.error);
            return (
              stream?.events.some(
                (event) =>
                  event !== null && typeof event === 'object' && 'id' in event && event.id === id,
              ) ?? false
            );
          }, notificationId),
        { timeout: 60_000 },
      )
      .toBe(true);
  }

  /** Stops only the stream opened by this test. */
  public async unsubscribe(): Promise<void> {
    await this.page.evaluate(() => window.fgLiveStream?.controller.abort());
  }
}
