import type { HydraItem } from '@core/api/models';
import type { FacilityType } from '@features/organization/features/facilities/models';
import type {
  InspectionResult,
  InspectionStatus,
  InspectorType,
  NonConformitySeverity,
  NonConformityStatus,
} from '@features/organization/features/inspections/models';
import type { OrganizationDashboardPeriod } from './organization-dashboard-output.interface';
import type {
  OrganizationDashboardEquipmentStatus,
  OrganizationDashboardEquipmentType,
  OrganizationDashboardGranularity,
} from './organization-dashboard-query-options.interface';

/**
 * Type OrganizationDashboardTrendKey
 *
 * @description
 * Supported dashboard trend resource keys exposed by the
 * organization dashboard API.
 *
 * @type {OrganizationDashboardTrendKey}
 */
export type OrganizationDashboardTrendKey =
  | 'inspections'
  | 'nonConformitiesOpened'
  | 'nonConformitiesResolved'
  | 'equipmentCreated'
  | 'facilitiesCreated';

/**
 * Type OrganizationDashboardTrendSummaryValue
 *
 * @description
 * Primitive value supported inside the summary
 * block of a dashboard trend payload.
 *
 * @type {OrganizationDashboardTrendSummaryValue}
 */
export type OrganizationDashboardTrendSummaryValue = number | string;

/**
 * Type OrganizationDashboardTrendSummary
 *
 * @description
 * Summary metrics returned alongside a trend series,
 * keyed by backend-defined field names.
 *
 * @type {OrganizationDashboardTrendSummary}
 */
export type OrganizationDashboardTrendSummary = Readonly<
  Record<string, OrganizationDashboardTrendSummaryValue>
>;

/**
 * Type OrganizationDashboardTrendSeriesPointValue
 *
 * @description
 * Primitive value supported inside one trend-series point.
 *
 * @type {OrganizationDashboardTrendSeriesPointValue}
 */
export type OrganizationDashboardTrendSeriesPointValue = number | string;

/**
 * Type OrganizationDashboardTrendSeriesPoint
 *
 * @description
 * One data point in a dedicated dashboard trend series.
 *
 * @type {OrganizationDashboardTrendSeriesPoint}
 */
export type OrganizationDashboardTrendSeriesPoint = Readonly<
  Record<string, OrganizationDashboardTrendSeriesPointValue>
>;

/**
 * Type OrganizationDashboardTrendComparisonScalarMap
 *
 * @description
 * Named numeric values returned inside the trend
 * comparison block.
 *
 * @type {OrganizationDashboardTrendComparisonScalarMap}
 */
export type OrganizationDashboardTrendComparisonScalarMap = Readonly<Record<string, number>>;

/**
 * Type OrganizationDashboardTrendComparisonValue
 *
 * @description
 * Value returned inside the dashboard trend comparison object.
 *
 * @type {OrganizationDashboardTrendComparisonValue}
 */
export type OrganizationDashboardTrendComparisonValue =
  | OrganizationDashboardTrendComparisonScalarMap
  | readonly OrganizationDashboardTrendSeriesPoint[]
  | string
  | null;

/**
 * Type OrganizationDashboardTrendComparison
 *
 * @description
 * Comparison block returned for a dashboard trend resource.
 *
 * @type {OrganizationDashboardTrendComparison}
 */
export type OrganizationDashboardTrendComparison = Readonly<
  Record<string, OrganizationDashboardTrendComparisonValue>
> & {
  readonly mode?: string | null;
  readonly from?: string | null;
  readonly to?: string | null;

  /**
   * @description
   * Period-total scalars (`total`, `delta`), not a series — a single
   * `{total?: int, delta?: float}` map per
   * `GetOrganizationDashboardTrendProvider::normalizeComparison()`.
   */
  readonly summary?: OrganizationDashboardTrendComparisonScalarMap;
  readonly series?: readonly OrganizationDashboardTrendSeriesPoint[];
};

/**
 * Interface OrganizationDashboardTrendOutput
 * @interface OrganizationDashboardTrendOutput
 *
 * @description
 * Dedicated dashboard trend payload returned by the
 * `/dashboard/trends/*` organization endpoints.
 */
export interface OrganizationDashboardTrendOutput extends HydraItem {
  //#region Properties
  /**
   * Property generatedAt
   * @readonly
   *
   * @description
   * Timestamp indicating when the trend payload
   * was generated by the backend.
   *
   * @type {string}
   */
  readonly generatedAt: string;

  /**
   * Property metric
   * @readonly
   *
   * @description
   * Backend metric identifier represented by this
   * dedicated trend resource.
   *
   * @type {string}
   */
  readonly metric: string;

  /**
   * Property period
   * @readonly
   *
   * @description
   * Period metadata used to compute the trend.
   *
   * @type {OrganizationDashboardPeriod}
   */
  readonly period: OrganizationDashboardPeriod;

  /**
   * Property summary
   * @readonly
   *
   * @description
   * Summary metrics associated with the trend
   * series.
   *
   * @type {OrganizationDashboardTrendSummary}
   */
  readonly summary: OrganizationDashboardTrendSummary;

  /**
   * Property series
   * @readonly
   *
   * @description
   * Ordered data points composing the trend series.
   *
   * @type {readonly OrganizationDashboardTrendSeriesPoint[]}
   */
  readonly series: readonly OrganizationDashboardTrendSeriesPoint[];

  /**
   * Property comparison
   * @readonly
   *
   * @description
   * Comparison payload against the previous period,
   * when requested by the client.
   *
   * @type {OrganizationDashboardTrendComparison}
   */
  readonly comparison: OrganizationDashboardTrendComparison;
  //#endregion
}

/**
 * Type OrganizationDashboardOverviewTrendResource
 *
 * @description
 * Shape of the `rxResource` value for the overview trend card,
 * which combines all three dashboard trend datasets in a single
 * parallel load.
 *
 * @type {OrganizationDashboardOverviewTrendResource}
 */
export type OrganizationDashboardOverviewTrendResource = {
  /**
   * Property inspections
   * @readonly
   *
   * @description
   * Trend dataset for inspection activity over the selected period.
   *
   * @access public
   * @since 0.1.0
   *
   * @type {OrganizationDashboardTrendOutput}
   */
  readonly inspections: OrganizationDashboardTrendOutput;

  /**
   * Property ncOpened
   * @readonly
   *
   * @description
   * Trend dataset for non-conformities opened over the selected period.
   *
   * @access public
   * @since 0.1.0
   *
   * @type {OrganizationDashboardTrendOutput}
   */
  readonly ncOpened: OrganizationDashboardTrendOutput;

  /**
   * Property ncResolved
   * @readonly
   *
   * @description
   * Trend dataset for non-conformities resolved over the selected period.
   *
   * @access public
   * @since 0.1.0
   *
   * @type {OrganizationDashboardTrendOutput}
   */
  readonly ncResolved: OrganizationDashboardTrendOutput;
};

/**
 * Type OrganizationDashboardTrendResourceParams
 *
 * @description
 * Reactive params shape shared by all trend `rxResource` instances.
 * Combines the active organization identifier with the selected
 * time granularity and optional date range / comparison flag
 * to drive automatic re-fetching.
 *
 * @type {OrganizationDashboardTrendResourceParams}
 */
export type OrganizationDashboardTrendResourceParams = {
  /**
   * Property organizationId
   * @readonly
   *
   * @description
   * Organization whose trend data is being requested.
   *
   * @access public
   * @since 0.1.0
   *
   * @type {string}
   */
  readonly organizationId: string;

  /**
   * Property granularity
   * @readonly
   *
   * @description
   * Time bucket size used to group the trend points.
   *
   * @access public
   * @since 0.1.0
   *
   * @type {OrganizationDashboardGranularity}
   */
  readonly granularity: OrganizationDashboardGranularity;

  /**
   * Property from
   * @readonly
   *
   * @description
   * Optional inclusive start date for the requested range.
   *
   * @access public
   * @since 0.1.0
   *
   * @type {string | undefined}
   */
  readonly from?: string;

  /**
   * Property to
   * @readonly
   *
   * @description
   * Optional inclusive end date for the requested range.
   *
   * @access public
   * @since 0.1.0
   *
   * @type {string | undefined}
   */
  readonly to?: string;

  /**
   * Property compare
   * @readonly
   *
   * @description
   * Whether the trend response includes a comparison period.
   *
   * @access public
   * @since 0.1.0
   *
   * @type {boolean | undefined}
   */
  readonly compare?: boolean;
};

/**
 * Type OrganizationDashboardInspectionTrendResourceParams
 *
 * @description
 * Reactive params shape for the inspections trend `rxResource`.
 * Extends the base params with inspection-specific filters.
 *
 * @type {OrganizationDashboardInspectionTrendResourceParams}
 */
export type OrganizationDashboardInspectionTrendResourceParams =
  OrganizationDashboardTrendResourceParams & {
    readonly inspectionStatus?: InspectionStatus;
    readonly inspectionResult?: InspectionResult;
    readonly inspectorType?: InspectorType;
  };

/**
 * Type OrganizationDashboardNonConformityTrendResourceParams
 *
 * @description
 * Reactive params shape for the non-conformity trend `rxResource` instances.
 * Extends the base params with non-conformity-specific filters.
 *
 * @type {OrganizationDashboardNonConformityTrendResourceParams}
 */
export type OrganizationDashboardNonConformityTrendResourceParams =
  OrganizationDashboardTrendResourceParams & {
    readonly nonConformityStatus?: NonConformityStatus;
    readonly nonConformitySeverity?: NonConformitySeverity;
  };

/**
 * Type OrganizationDashboardEquipmentTrendResourceParams
 *
 * @description
 * Reactive params shape for the equipment-created trend `rxResource`.
 * Extends the base params with equipment-specific filters.
 *
 * @type {OrganizationDashboardEquipmentTrendResourceParams}
 */
export type OrganizationDashboardEquipmentTrendResourceParams =
  OrganizationDashboardTrendResourceParams & {
    readonly equipmentType?: OrganizationDashboardEquipmentType;
    readonly equipmentStatus?: OrganizationDashboardEquipmentStatus;
  };

/**
 * Type OrganizationDashboardFacilityTrendResourceParams
 *
 * @description
 * Reactive params shape for the facilities-created trend `rxResource`.
 * Extends the base params with facility-specific filters.
 *
 * @type {OrganizationDashboardFacilityTrendResourceParams}
 */
export type OrganizationDashboardFacilityTrendResourceParams =
  OrganizationDashboardTrendResourceParams & {
    readonly facilityType?: FacilityType;
  };
