export {
  SHELL_RAIL_WIDTH_PX,
  SHELL_SIDEBAR_WIDTH_PX,
  SHELL_PANEL_WIDTH_PX,
  SHELL_INLINE_NAV_MIN_WIDTH_PX,
  SHELL_INLINE_PANEL_MIN_WIDTH_PX,
  SHELL_SECOND_PANEL_MIN_WIDTH_PX,
} from './shell-geometry.constants';
