/**
 * Interface ConfirmTotpInput
 * @interface ConfirmTotpInput
 *
 * @description
 * Payload for `POST /api/otp/totp/confirm`: the code generated by the
 * authenticator app for the pending secret created by the setup call.
 *
 * @since 1.0.0
 */
export interface ConfirmTotpInput {
  /** 6-digit TOTP code generated by the authenticator app. */
  readonly code: string;
}
