#!/usr/bin/env node
/**
 * PreToolUse hook — enforce the FireGuard git conventions before a shell command
 * runs. Deny = exit 2 with the expected shape on stderr; everything else = exit 0.
 *
 * The third guard: guard.mjs watches what gets written, guard-delete.mjs what gets
 * destroyed, this one what gets *named*. It reads `tool_input.command` from Bash
 * and PowerShell calls and checks two things only:
 *
 *  1. Branch names created by checkout -b / switch -c / branch <name> / worktree
 *     add -b, and renames via branch -m.
 *  2. The header line of `git commit -m`, against Conventional Commits — which is
 *     what the history of both repos already does, and what git-cliff reads to
 *     build the release notes.
 *
 * Two exemptions are load-bearing:
 *  - `codex/*` and `claude/*` branches are generated by the coding tools (sessions, cloud runs,
 *    worktrees). Rejecting them would make the guard fight the tool that created
 *    them, on every session.
 *  - `main`, `develop` and `release/x.y.z` are the long-lived branches; `git checkout
 *    -b develop origin/develop` is a legitimate local re-creation, not a new feature.
 *
 * Parsing is deliberately conservative: when the message or the name cannot be
 * extracted with confidence, the hook exits 0. A guard with false positives is a
 * guard people disable.
 *
 * Bypass: run the command yourself, or `git commit --no-verify` for the git-side
 * twin in .githooks/.
 */

/** Conventional Commits types, shared by the branch prefix and the commit header. */
const TYPES = 'feat|fix|chore|refactor|docs|test|perf|ci|build|style|revert';

/** `<type>/<description-kebab>` — lowercase, digits, single hyphens, no trailing hyphen. */
const BRANCH_OK = new RegExp(`^(?:${TYPES}|hotfix)/[a-z0-9]+(?:-[a-z0-9]+)*$`);

/** Names no convention should ever reject. */
const BRANCH_EXEMPT = /^(?:main|develop|(?:claude|codex)\/.+|release\/\d+\.\d+\.\d+)$/;

/**
 * `<type>(<scope>)!: <subject>` — scope optional, subject starts lowercase.
 * The 100-character cap is commitlint's default, not 72: the existing history has
 * legitimate 76-character headers that a tighter cap would have rejected.
 */
const COMMIT_OK = new RegExp(`^(?:${TYPES})(?:\\([a-z0-9][a-z0-9._/-]*\\))?!?: [a-z].*$`);

/** Machine-generated headers that are not the author's to shape. */
const COMMIT_EXEMPT = /^(?:Merge\b|Revert\b|fixup!|squash!|Initial commit$)/;

function readStdin() {
  return new Promise((resolve) => {
    let data = '';
    process.stdin.on('data', (chunk) => (data += chunk));
    process.stdin.on('end', () => resolve(data));
    if (process.stdin.isTTY) resolve('');
  });
}

function deny(what, why) {
  process.stderr.write(`Blocked: ${what}\n${why}\n`);
  process.exit(2);
}

const raw = await readStdin();
let payload = {};
try {
  payload = JSON.parse(raw || '{}');
} catch {
  process.exit(0);
}

const command = payload?.tool_input?.command ?? '';
if (!command || !/\bgit\b/.test(command)) process.exit(0);

/**
 * `git` in *command position* — at the start, or after a shell separator — plus the
 * optional `-C <path>` before the subcommand.
 *
 * The anchor is what keeps the guard from firing on a command that merely contains
 * the text: `node -e '… "git checkout -b " + name …'`, a heredoc documenting the
 * convention, an error message quoting it. There `git` follows a quote or a plain
 * space, never a separator, so nothing matches — and nothing is blocked, because
 * nothing is being created.
 */
const GIT = String.raw`(?:^|[;&|(\n])\s*(?:sudo\s+|env\s+\S+=\S+\s+)*git\b(?:\s+-C\s+\S+)?\s+`;
/** A branch name as it appears on the command line, quoted or bare. */
const NAME = String.raw`(?:"([^"]+)"|'([^']+)'|([^\s"'&|;]+))`;

/** First non-empty capture group of a match. */
const captured = (m) => m[1] ?? m[2] ?? m[3] ?? '';

/**
 * What the branch patterns actually scan: the command with the arguments of `echo`
 * and `printf` removed. A command that merely *prints* `git checkout -b foo` —
 * documentation, a test harness, an error message — creates no branch, and blocking
 * it is the kind of false positive that gets a guard switched off. The argument
 * match stops at a shell separator, so `echo hi && git checkout -b bad` still gets
 * caught on its real half.
 */
const scanned = command.replace(/\b(?:echo|printf)\s+(?:"[^"]*"|'[^']*'|[^|;&\n]*)/g, ' ');

// #region branch names

const CREATED = [
  new RegExp(`${GIT}checkout\\s+(?:-b|-B)\\s+${NAME}`, 'g'),
  new RegExp(`${GIT}switch\\s+(?:-c|-C|--create)\\s+${NAME}`, 'g'),
  new RegExp(`${GIT}worktree\\s+add\\s+(?:[^\\s|;&]+\\s+)*?-b\\s+${NAME}`, 'g'),
  // `git branch <name>` — creation only. The negative lookahead drops the listing
  // and deletion forms (-a, --list, -d), which take an option, not a new name.
  new RegExp(`${GIT}branch\\s+(?!-)${NAME}`, 'g'),
  // `git branch -m <new>` or `-m <old> <new>`: the destination is the last token.
  new RegExp(`${GIT}branch\\s+(?:-m|-M|--move)\\s+(?:[^\\s"'&|;-]\\S*\\s+)?${NAME}`, 'g'),
];

for (const pattern of CREATED) {
  for (const match of scanned.matchAll(pattern)) {
    const name = captured(match).trim();
    if (!name || BRANCH_EXEMPT.test(name) || BRANCH_OK.test(name)) continue;
    deny(
      `branch name "${name}" — ${command}`,
      'Branches follow <type>/<description-kebab>, e.g. feat/organization-invitations or ' +
        `fix/otp-expiry.\nType is one of: ${TYPES.split('|').join(', ')}, hotfix. ` +
        'The description is lowercase words joined by single hyphens.',
    );
  }
}

// #endregion

// #region commit headers

if (new RegExp(`${GIT}commit\\b`).test(command)) {
  const message = command.match(/(?:-m|--message)[ =]+(?:"([\s\S]*?)"|'([\s\S]*?)'|(\S+))/);
  if (message) {
    let value = captured(message);
    // `-m "$(cat <<'EOF' … EOF)"` — the header is the first line of the heredoc body,
    // which starts after the marker line.
    if (value.startsWith('$(')) value = value.slice(value.indexOf('\n') + 1);
    const header = value.split('\n')[0].trim();

    if (header && !COMMIT_EXEMPT.test(header)) {
      if (!COMMIT_OK.test(header)) {
        deny(
          `commit header "${header}"`,
          'Commit headers follow Conventional Commits: <type>(<scope>): <subject>, e.g. ' +
            `feat(organization): expose granted role names.\nType is one of: ${TYPES.split('|').join(', ')}. ` +
            'The scope is the module or feature; the subject starts lowercase and is imperative.',
        );
      }
      if (header.length > 100) {
        deny(
          `commit header of ${header.length} characters`,
          'Keep the header under 100 characters and move the detail to the body.',
        );
      }
      if (header.endsWith('.')) {
        deny(`commit header ending in a period — "${header}"`, 'Headers carry no trailing period.');
      }
    }
  }
}

// #endregion

process.exit(0);
