import type { HydraItem } from '@core/api/models';

/**
 * Type FederatedProvider
 * @type FederatedProvider
 *
 * @description
 * External identity providers supported by the Fireguard API contract.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export type FederatedProvider = 'google' | 'microsoft';

/**
 * Type FederatedAuthErrorCode
 * @type FederatedAuthErrorCode
 *
 * @description
 * Stable federation and first-password failure codes returned by the Auth API.
 * Keeping this union beside the transport contracts prevents presentation code
 * from treating backend details as arbitrary user-facing copy.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export type FederatedAuthErrorCode =
  | 'account_exists'
  | 'account_unavailable'
  | 'email_missing'
  | 'email_unverified'
  | 'expired'
  | 'identity_linked'
  | 'identity_missing'
  | 'invalid_code'
  | 'invalid_flow'
  | 'invalid_token'
  | 'last_sign_in_method'
  | 'max_attempts_exceeded'
  | 'password_already_configured'
  | 'provider_already_linked'
  | 'provider_cancelled'
  | 'federated_auth_failed'
  | 'provider_unavailable'
  | 'unknown_provider';

/**
 * Type SignInMethod
 * @type SignInMethod
 *
 * @description
 * Credential families that can remain as a usable sign-in method.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export type SignInMethod = FederatedProvider | 'password';

/**
 * Interface FederatedProviderOutput
 * @interface FederatedProviderOutput
 *
 * @description
 * Public provider availability returned during login SSR and hydration.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface FederatedProviderOutput extends HydraItem {
  /**
   * Property provider
   * @readonly
   * @description Stable provider identifier used in routes and transport calls.
   * @access public
   * @since 1.0.0
   * @type {FederatedProvider}
   */
  readonly provider: FederatedProvider;

  /**
   * Property enabled
   * @readonly
   * @description Whether the provider is configured and available for sign-in.
   * @access public
   * @since 1.0.0
   * @type {boolean}
   */
  readonly enabled: boolean;
}

/**
 * Interface FederatedStartInput
 * @interface FederatedStartInput
 *
 * @description
 * Local destination requested when beginning a full-page provider redirect.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface FederatedStartInput {
  /**
   * Property return_url
   * @readonly
   * @description Application-relative path restored after authentication succeeds.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly return_url: string;
}

/**
 * Interface FederatedStartOutput
 * @interface FederatedStartOutput
 *
 * @description
 * Provider authorization location generated by the backend.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface FederatedStartOutput extends HydraItem {
  /**
   * Property authorization_url
   * @readonly
   * @description Trusted URL used for the full-page OAuth redirect.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly authorization_url: string;
}

/**
 * Interface FederatedCompleteSuccessInput
 * @interface FederatedCompleteSuccessInput
 *
 * @description Successful provider callback submitted for one-time exchange.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface FederatedCompleteSuccessInput {
  /**
   * Property code
   * @readonly
   * @description Short-lived authorization code returned by the provider.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly code: string;

  /**
   * Property error
   * @readonly
   * @description Excluded from a successful callback payload.
   * @access public
   * @since 1.0.0
   * @type {never}
   */
  readonly error?: never;

  /**
   * Property state
   * @readonly
   * @description Opaque state value matching the backend-owned login flow.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly state: string;
}

/**
 * Interface FederatedCompleteErrorInput
 * @interface FederatedCompleteErrorInput
 *
 * @description Provider cancellation or error submitted so the backend can consume the flow.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface FederatedCompleteErrorInput {
  /**
   * Property code
   * @readonly
   * @description Excluded from a provider-error callback payload.
   * @access public
   * @since 1.0.0
   * @type {never}
   */
  readonly code?: never;

  /**
   * Property error
   * @readonly
   * @description Provider error identifier returned with the callback.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly error: string;

  /**
   * Property state
   * @readonly
   * @description Opaque state value matching the backend-owned login flow.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly state: string;
}

/**
 * Type FederatedCompleteInput
 * @type FederatedCompleteInput
 *
 * @description Discriminated provider callback accepted by the Auth completion endpoints.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export type FederatedCompleteInput = FederatedCompleteErrorInput | FederatedCompleteSuccessInput;

/**
 * Interface FederatedConnectionOutput
 * @interface FederatedConnectionOutput
 *
 * @description
 * One provider identity explicitly connected to a Fireguard user.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface FederatedConnectionOutput {
  /**
   * Property provider
   * @readonly
   *
   * @description Provider that owns the external identity.
   * @access public
   * @since 1.0.0
   * @type {FederatedProvider}
   */
  readonly provider: FederatedProvider;
  /**
   * Property email
   * @readonly
   *
   * @description Email observed when the identity was connected.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly email: string;
  /**
   * Property connected_at
   * @readonly
   *
   * @description ISO timestamp recording when the provider was connected.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly connected_at: string;
  /**
   * Property last_used_at
   * @readonly
   *
   * @description ISO timestamp of the latest successful provider sign-in.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly last_used_at: string;
}

/**
 * Interface FederatedConnectionsOutput
 * @interface FederatedConnectionsOutput
 *
 * @description
 * Authenticated view of the user's available sign-in methods.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface FederatedConnectionsOutput extends HydraItem {
  /**
   * Property password_configured
   * @readonly
   *
   * @description Whether a usable local password exists.
   * @access public
   * @since 1.0.0
   * @type {boolean}
   */
  readonly password_configured: boolean;
  /**
   * Property last_sign_in_method
   * @readonly
   *
   * @description Latest successful credential family when known.
   * @access public
   * @since 1.0.0
   * @type {SignInMethod | null}
   */
  readonly last_sign_in_method: SignInMethod | null;
  /**
   * Property connections
   * @readonly
   *
   * @description External identities connected to the account.
   * @access public
   * @since 1.0.0
   * @type {readonly FederatedConnectionOutput[]}
   */
  readonly connections: readonly FederatedConnectionOutput[];
}

/**
 * Interface PasswordSetupChallengeOutput
 * @interface PasswordSetupChallengeOutput
 *
 * @description
 * Email OTP challenge created before setting a first local password.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface PasswordSetupChallengeOutput extends HydraItem {
  /**
   * Property success
   * @readonly
   *
   * @description Whether the challenge was created.
   * @access public
   * @since 1.0.0
   * @type {boolean}
   */
  readonly success: boolean;
  /**
   * Property message
   * @readonly
   *
   * @description User-facing challenge status.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly message: string;
  /**
   * Property challengeToken
   * @readonly
   *
   * @description Opaque token submitted with the OTP.
   * @access public
   * @since 1.0.0
   * @type {string | null}
   */
  readonly challengeToken: string | null;
  /**
   * Property maskedRecipient
   * @readonly
   *
   * @description Masked email destination shown to the user.
   * @access public
   * @since 1.0.0
   * @type {string | null}
   */
  readonly maskedRecipient: string | null;
  /**
   * Property expiresAt
   * @readonly
   *
   * @description ISO timestamp after which the challenge is invalid.
   * @access public
   * @since 1.0.0
   * @type {string | null}
   */
  readonly expiresAt: string | null;
  /**
   * Property maxAttempts
   * @readonly
   *
   * @description Maximum OTP verification attempts.
   * @access public
   * @since 1.0.0
   * @type {number | null}
   */
  readonly maxAttempts: number | null;
}

/**
 * Interface PasswordSetupConfirmInput
 * @interface PasswordSetupConfirmInput
 *
 * @description
 * Verification values required to configure a first password.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface PasswordSetupConfirmInput {
  /**
   * Property token
   * @readonly
   *
   * @description Opaque challenge token returned by the setup request.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly token: string;
  /**
   * Property code
   * @readonly
   *
   * @description Six-digit email verification code.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly code: string;
  /**
   * Property newPassword
   * @readonly
   *
   * @description New local password satisfying Fireguard rules.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly newPassword: string;
}

/**
 * Interface PasswordSetupConfirmOutput
 * @interface PasswordSetupConfirmOutput
 *
 * @description
 * Result of the first-password OTP verification and mutation.
 *
 * @version 1.0.0
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
export interface PasswordSetupConfirmOutput extends HydraItem {
  /**
   * Property success
   * @readonly
   *
   * @description Whether the password was configured.
   * @access public
   * @since 1.0.0
   * @type {boolean}
   */
  readonly success: boolean;
  /**
   * Property message
   * @readonly
   *
   * @description User-facing completion status.
   * @access public
   * @since 1.0.0
   * @type {string}
   */
  readonly message: string;
  /**
   * Property errorCode
   * @readonly
   *
   * @description Stable failure code when verification fails.
   * @access public
   * @since 1.0.0
   * @type {string | null}
   */
  readonly errorCode: FederatedAuthErrorCode | null;
  /**
   * Property attemptsRemaining
   * @readonly
   *
   * @description Remaining OTP attempts after the response.
   * @access public
   * @since 1.0.0
   * @type {number}
   */
  readonly attemptsRemaining: number;
}
