import type { BooleanInput } from '@angular/cdk/coercion';
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideChevronDown } from '@ng-icons/lucide';
import { BrnFieldControlDescribedBy } from '@spartan-ng/brain/field';
import { BrnSelectTrigger } from '@spartan-ng/brain/select';
import type { ClassValue } from 'clsx';
import { hlm } from '@shared/ui/utils';

/**
 * Component HlmSelectTrigger
 * @class HlmSelectTrigger
 *
 * @description
 * Generated by `npx ng g @spartan-ng/cli:ui select` — vendored, ours to
 * edit, never to reshape (`ARCHITECTURE.md` §8.5). {@link buttonId} and
 * `class` already reach the inner `<button>` because the generator itself
 * aliased them there; a plain `[attr.aria-disabled]` written on
 * `<hlm-select-trigger>` does not, and never will, because Angular applies
 * an `[attr.x]` binding only to the literal element it is written on — never
 * through to a child. {@link ariaDisabled} is the deliberate fix, added past
 * the generator's own output: a caller that needs the value on the actual
 * focusable, clickable `<button>` — the node a screen reader actually
 * reaches — binds this instead. It does not replace a caller's existing
 * `[attr.aria-disabled]` on the wrapper, which keeps resolving there exactly
 * as before; at least one caller (`FilterChip`, `@shared/collection-filters`)
 * depends on that for Playwright locator uniqueness. Unlike
 * `@shared/ui/combobox`'s `HlmComboboxTrigger`, whose `BrnComboboxTrigger`
 * binds its own competing `[attr.aria-disabled]` on the same `<button>` and
 * therefore needs an imperative post-render write to win the race,
 * `BrnSelectTrigger` (`@spartan-ng/brain/select`) binds only `[disabled]` —
 * no `aria-disabled` of its own — so a plain template binding here has
 * nothing to race. Regenerating this component with the CLI overwrites this
 * file and silently erases the fix; re-apply it after any regeneration.
 *
 * @since 10.5.0 — {@link ariaDisabled}
 *
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
@Component({
  selector: 'hlm-select-trigger',
  imports: [NgIcon, BrnSelectTrigger, BrnFieldControlDescribedBy],
  providers: [provideIcons({ lucideChevronDown })],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      brnSelectTrigger
      brnFieldControlDescribedBy
      [forceInvalid]="forceInvalid()"
      [id]="buttonId()"
      [class]="_computedClass()"
      [attr.data-size]="size()"
      [attr.aria-disabled]="ariaDisabled() ? 'true' : null"
      data-slot="select-trigger"
    >
      <ng-content />
      <ng-icon
        name="lucideChevronDown"
        class="ms-auto text-[length:--spacing(4)] text-muted-foreground"
      />
    </button>
  `,
})
export class HlmSelectTrigger {
  private static _id = 0;

  public readonly userClass = input<ClassValue>('', { alias: 'class' });
  protected readonly _computedClass = computed(() =>
    hlm(
      'border-input data-placeholder:text-muted-foreground dark:bg-input/30 dark:hover:bg-input/50 focus-visible:border-ring focus-visible:ring-ring/50 data-[matches-spartan-invalid=true]:ring-destructive/20 dark:data-[matches-spartan-invalid=true]:ring-destructive/40 data-[matches-spartan-invalid=true]:border-destructive dark:data-[matches-spartan-invalid=true]:border-destructive/50 gap-1.5 rounded-lg border bg-transparent py-2 ps-2.5 pe-2 text-sm transition-colors focus-visible:ring-3 data-[matches-spartan-invalid=true]:ring-3 data-[size=default]:h-8 data-[size=sm]:h-7 data-[size=sm]:rounded-[min(var(--radius-md),10px)] *:data-[slot=select-value]:gap-1.5 flex w-fit items-center justify-between whitespace-nowrap outline-none disabled:cursor-not-allowed disabled:opacity-50 *:data-[slot=select-value]:line-clamp-1 *:data-[slot=select-value]:flex *:data-[slot=select-value]:items-center [&_ng-icon]:pointer-events-none [&_ng-icon]:shrink-0',
      this.userClass(),
    ),
  );

  public readonly buttonId = input<string>(`hlm-select-trigger-${HlmSelectTrigger._id++}`);

  public readonly size = input<'default' | 'sm'>('default');

  /** Whether to force the trigger into an invalid state. */
  public readonly forceInvalid = input<boolean, BooleanInput>(false, {
    transform: booleanAttribute,
  });

  /**
   * Property ariaDisabled
   * @readonly
   * @description Reaches the inner `<button>`'s `aria-disabled`, unlike a plain `[attr.aria-disabled]` on this wrapper — see the class doc.
   * @access public
   * @since 10.5.0
   * @type {InputSignal<boolean>}
   */
  public readonly ariaDisabled = input<boolean, BooleanInput>(false, {
    transform: booleanAttribute,
  });
}
