import { BooleanInput } from '@angular/cdk/coercion';
import {
  afterRenderEffect,
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  viewChild,
  type AfterRenderRef,
  type Signal,
} from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideChevronDown } from '@ng-icons/lucide';
import {
  BrnComboboxAnchor,
  BrnComboboxPopoverTrigger,
  BrnComboboxTrigger,
} from '@spartan-ng/brain/combobox';
import { BrnFieldControlDescribedBy } from '@spartan-ng/brain/field';
import type { ClassValue } from 'clsx';
import { ButtonVariants, HlmButton } from '@shared/ui/button';
import { hlm } from '@shared/ui/utils';

/**
 * Component HlmComboboxTrigger
 * @class HlmComboboxTrigger
 *
 * @description
 * Generated by `npx ng g @spartan-ng/cli:ui combobox` — vendored, ours to
 * edit, never to reshape (`ARCHITECTURE.md` §8.5). {@link buttonId} and
 * `class` already reach the inner `<button>` because the generator itself
 * aliased them there; a plain `[attr.aria-disabled]` written on
 * `<hlm-combobox-trigger>` does not, and never will, because Angular applies
 * an `[attr.x]` binding only to the literal element it is written on — never
 * through to a child. {@link ariaDisabled} is the deliberate fix, added past
 * the generator's own output: a caller that needs the value on the actual
 * focusable, clickable `<button>` — the node a screen reader actually
 * reaches — binds this instead. It does not replace a caller's existing
 * `[attr.aria-disabled]` on the wrapper, which keeps resolving there exactly
 * as before. `BrnComboboxTrigger` (matched on the same `<button>`) binds its
 * own `[attr.aria-disabled]` from its internal `_disabled()` state, so a
 * plain `[attr.aria-disabled]` written directly in this template would race
 * that binding on every change-detection pass with no guaranteed winner;
 * {@link ariaDisabled} is therefore applied imperatively, in
 * `afterRenderEffect`'s `write` phase — strictly after Angular's own binding
 * pass for that render — so it is always the value that actually sticks.
 * Regenerating this component with the CLI overwrites this file and silently
 * erases the fix; re-apply it after any regeneration.
 *
 * @since 10.5.0 — {@link ariaDisabled}
 *
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
@Component({
  selector: 'hlm-combobox-trigger',
  imports: [
    NgIcon,
    HlmButton,
    BrnComboboxAnchor,
    BrnComboboxTrigger,
    BrnComboboxPopoverTrigger,
    BrnFieldControlDescribedBy,
  ],
  providers: [provideIcons({ lucideChevronDown })],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      #triggerButton
      brnComboboxTrigger
      brnComboboxAnchor
      brnComboboxPopoverTrigger
      brnFieldControlDescribedBy
      hlmBtn
      data-slot="combobox-trigger"
      [id]="buttonId()"
      [class]="_computedClass()"
      [variant]="variant()"
      [forceInvalid]="forceInvalid()"
    >
      <ng-content />
      <ng-icon name="lucideChevronDown" class="text-[length:--spacing(4)] text-muted-foreground" />
    </button>
  `,
})
export class HlmComboboxTrigger {
  private static _id = 0;

  public readonly userClass = input<ClassValue>('', {
    alias: 'class',
  });
  protected readonly _computedClass = computed(() =>
    hlm('data-placeholder:text-muted-foreground', this.userClass()),
  );

  public readonly buttonId = input<string>(`hlm-combobox-trigger-${HlmComboboxTrigger._id++}`);

  public readonly variant = input<ButtonVariants['variant']>('outline');

  public readonly forceInvalid = input<boolean, BooleanInput>(false, {
    transform: booleanAttribute,
  });

  /**
   * Property ariaDisabled
   * @readonly
   * @description Reaches the inner `<button>`'s `aria-disabled`, unlike a plain `[attr.aria-disabled]` on this wrapper — see the class doc.
   * @access public
   * @since 10.5.0
   * @type {InputSignal<boolean>}
   */
  public readonly ariaDisabled = input<boolean, BooleanInput>(false, {
    transform: booleanAttribute,
  });

  /**
   * Property triggerButtonRef
   * @readonly
   * @description This trigger's own inner `<button>`, so {@link syncButtonAttrs} can write to it directly.
   * @access private
   * @since 10.5.0
   * @type {Signal<ElementRef<HTMLButtonElement> | undefined>}
   */
  private readonly triggerButtonRef: Signal<ElementRef<HTMLButtonElement> | undefined> =
    viewChild<ElementRef<HTMLButtonElement>>('triggerButton');

  /**
   * Property syncButtonAttrs
   * @readonly
   * @description Re-asserts {@link ariaDisabled} on the inner `<button>` after every render — see the class doc for why an imperative, post-render write is what makes `aria-disabled` stick against `BrnComboboxTrigger`'s own competing binding.
   * @access private
   * @since 10.5.0
   * @type {AfterRenderRef}
   */
  private readonly syncButtonAttrs: AfterRenderRef = afterRenderEffect({
    write: (): void => {
      const button: HTMLButtonElement | undefined = this.triggerButtonRef()?.nativeElement;
      if (!button) return;

      button.setAttribute('aria-disabled', this.ariaDisabled() ? 'true' : 'false');
    },
  });
}
