import type { HydraItem } from '@core/models/api';
import type {
  OrganizationDashboardEquipmentStatus,
  OrganizationDashboardEquipmentType,
  OrganizationDashboardGranularity,
} from './organization-dashboard-query-options.interface';
import type {
  InspectionResult,
  InspectionStatus,
  InspectorType,
} from '../inspection/inspection-output.interface';
import type {
  NonConformitySeverity,
  NonConformityStatus,
} from '../inspection/non-conformity-output.interface';
import type { FacilityType } from '../facility/facility-output.interface';
import type { OrganizationDashboardPeriod } from './organization-dashboard-output.interface';

/**
 * Type OrganizationDashboardTrendKey
 *
 * @description
 * Supported dashboard trend resource keys exposed by the
 * organization dashboard API.
 */
export type OrganizationDashboardTrendKey =
  | 'inspections'
  | 'nonConformitiesOpened'
  | 'nonConformitiesResolved'
  | 'equipmentCreated'
  | 'facilitiesCreated';

/**
 * Type OrganizationDashboardTrendSummaryValue
 *
 * @description
 * Primitive value supported inside the summary
 * block of a dashboard trend payload.
 */
export type OrganizationDashboardTrendSummaryValue = number | string;

/**
 * Type OrganizationDashboardTrendSummary
 *
 * @description
 * Summary metrics returned alongside a trend series,
 * keyed by backend-defined field names.
 */
export type OrganizationDashboardTrendSummary = Readonly<
  Record<string, OrganizationDashboardTrendSummaryValue>
>;

/**
 * Type OrganizationDashboardTrendSeriesPointValue
 *
 * @description
 * Primitive value supported inside one trend-series point.
 */
export type OrganizationDashboardTrendSeriesPointValue = number | string;

/**
 * Type OrganizationDashboardTrendSeriesPoint
 *
 * @description
 * One data point in a dedicated dashboard trend series.
 */
export type OrganizationDashboardTrendSeriesPoint = Readonly<
  Record<string, OrganizationDashboardTrendSeriesPointValue>
>;

/**
 * Type OrganizationDashboardTrendComparisonScalarValue
 *
 * @description
 * Numeric scalar value supported inside one trend
 * comparison summary map.
 */
export type OrganizationDashboardTrendComparisonScalarValue = number;

/**
 * Type OrganizationDashboardTrendComparisonScalarMap
 *
 * @description
 * Named numeric values returned inside the trend
 * comparison block.
 */
export type OrganizationDashboardTrendComparisonScalarMap = Readonly<
  Record<string, OrganizationDashboardTrendComparisonScalarValue>
>;

/**
 * Type OrganizationDashboardTrendComparisonValue
 *
 * @description
 * Value returned inside the dashboard trend comparison object.
 */
export type OrganizationDashboardTrendComparisonValue =
  | OrganizationDashboardTrendComparisonScalarMap
  | readonly OrganizationDashboardTrendSeriesPoint[]
  | string
  | null;

/**
 * Type OrganizationDashboardTrendComparison
 *
 * @description
 * Comparison block returned for a dashboard trend resource.
 */
export type OrganizationDashboardTrendComparison = Readonly<
  Record<string, OrganizationDashboardTrendComparisonValue>
> & {
  readonly mode?: string | null;
  readonly from?: string | null;
  readonly to?: string | null;
  readonly summary?: readonly OrganizationDashboardTrendSeriesPoint[];
  readonly series?: readonly OrganizationDashboardTrendSeriesPoint[];
};

/**
 * Interface OrganizationDashboardTrendOutput
 * @interface OrganizationDashboardTrendOutput
 *
 * @description
 * Dedicated dashboard trend payload returned by the
 * `/dashboard/trends/*` organization endpoints.
 */
export interface OrganizationDashboardTrendOutput extends HydraItem {
  //#region Properties
  /**
   * Property generatedAt
   * @readonly
   *
   * @description
   * Timestamp indicating when the trend payload
   * was generated by the backend.
   *
   * @type {string}
   */
  readonly generatedAt: string;

  /**
   * Property metric
   * @readonly
   *
   * @description
   * Backend metric identifier represented by this
   * dedicated trend resource.
   *
   * @type {string}
   */
  readonly metric: string;

  /**
   * Property period
   * @readonly
   *
   * @description
   * Period metadata used to compute the trend.
   *
   * @type {OrganizationDashboardPeriod}
   */
  readonly period: OrganizationDashboardPeriod;

  /**
   * Property summary
   * @readonly
   *
   * @description
   * Summary metrics associated with the trend
   * series.
   *
   * @type {OrganizationDashboardTrendSummary}
   */
  readonly summary: OrganizationDashboardTrendSummary;

  /**
   * Property series
   * @readonly
   *
   * @description
   * Ordered data points composing the trend series.
   *
   * @type {readonly OrganizationDashboardTrendSeriesPoint[]}
   */
  readonly series: readonly OrganizationDashboardTrendSeriesPoint[];

  /**
   * Property comparison
   * @readonly
   *
   * @description
   * Comparison payload against the previous period,
   * when requested by the client.
   *
   * @type {OrganizationDashboardTrendComparison}
   */
  readonly comparison: OrganizationDashboardTrendComparison;
  //#endregion
}

/**
 * Type OrganizationDashboardOverviewTrendResource
 *
 * @description
 * Shape of the `rxResource` value for the overview trend card,
 * which combines all three dashboard trend datasets in a single
 * parallel load.
 */
export type OrganizationDashboardOverviewTrendResource = {
  readonly inspections: OrganizationDashboardTrendOutput;
  readonly ncOpened: OrganizationDashboardTrendOutput;
  readonly ncResolved: OrganizationDashboardTrendOutput;
};

/**
 * Type OrganizationDashboardTrendResourceParams
 *
 * @description
 * Reactive params shape shared by all trend `rxResource` instances.
 * Combines the active organization identifier with the selected
 * time granularity and optional date range / comparison flag
 * to drive automatic re-fetching.
 */
export type OrganizationDashboardTrendResourceParams = {
  readonly organizationId: string;
  readonly granularity: OrganizationDashboardGranularity;
  readonly from?: string;
  readonly to?: string;
  readonly compare?: boolean;
};

/**
 * Type OrganizationDashboardInspectionTrendResourceParams
 *
 * @description
 * Reactive params shape for the inspections trend `rxResource`.
 * Extends the base params with inspection-specific filters.
 */
export type OrganizationDashboardInspectionTrendResourceParams =
  OrganizationDashboardTrendResourceParams & {
    readonly inspectionStatus?: InspectionStatus;
    readonly inspectionResult?: InspectionResult;
    readonly inspectorType?: InspectorType;
  };

/**
 * Type OrganizationDashboardNonConformityTrendResourceParams
 *
 * @description
 * Reactive params shape for the non-conformity trend `rxResource` instances.
 * Extends the base params with non-conformity-specific filters.
 */
export type OrganizationDashboardNonConformityTrendResourceParams =
  OrganizationDashboardTrendResourceParams & {
    readonly nonConformityStatus?: NonConformityStatus;
    readonly nonConformitySeverity?: NonConformitySeverity;
  };

/**
 * Type OrganizationDashboardEquipmentTrendResourceParams
 *
 * @description
 * Reactive params shape for the equipment-created trend `rxResource`.
 * Extends the base params with equipment-specific filters.
 */
export type OrganizationDashboardEquipmentTrendResourceParams =
  OrganizationDashboardTrendResourceParams & {
    readonly equipmentType?: OrganizationDashboardEquipmentType;
    readonly equipmentStatus?: OrganizationDashboardEquipmentStatus;
  };

/**
 * Type OrganizationDashboardFacilityTrendResourceParams
 *
 * @description
 * Reactive params shape for the facilities-created trend `rxResource`.
 * Extends the base params with facility-specific filters.
 */
export type OrganizationDashboardFacilityTrendResourceParams =
  OrganizationDashboardTrendResourceParams & {
    readonly facilityType?: FacilityType;
  };
